### ISSUE TITLE
Service-map plugin fails when worker > 1

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/data-prepper#320]
**Describe the bug**
Whenever we configure the service-map worker to be more than 1, we get service-map MapB create failure which causes the data-prepper to crash.
**To Reproduce**
1. Set `workers:` to any value greater than 1 and run the data-prepper

**Additional context**
***Logs***
```
180640 [service-map-pipeline-process-worker-2-thread-2] ERROR com.amazon.dataprepper.pipeline.ProcessWorker  ? Encountered exception during pipeline processing
org.mapdb.DBException$FileLocked: File is already opened and is locked: data/service-map/db-1612972144653
at org.mapdb.volume.Volume.lockFile(Volume.java:495)
at org.mapdb.volume.MappedFileVol.<init>(MappedFileVol.java:88)
at org.mapdb.volume.MappedFileVol$MappedFileFactory.factory(MappedFileVol.java:64)
at org.mapdb.volume.MappedFileVol$MappedFileFactory.makeVolume(MappedFileVol.java:38)
at org.mapdb.StoreDirect$volume$1.invoke(StoreDirect.kt:77)
at org.mapdb.StoreDirect$volume$1.invoke(StoreDirect.kt:16)
at org.mapdb.StoreDirect.<init>(StoreDirect.kt:76)
at org.mapdb.StoreDirect$Companion.make(StoreDirect.kt:57)
at org.mapdb.StoreDirect$Companion.make$default(StoreDirect.kt:56)
at org.mapdb.DBMaker$Maker.make(DBMaker.kt:450)
at com.amazon.dataprepper.plugins.processor.state.MapDbProcessorState.<init>(MapDbProcessorState.java:39)
at com.amazon.dataprepper.plugins.processor.ServiceMapStatefulProcessor.rotateWindows(ServiceMapStatefulProcessor.java:298)
at com.amazon.dataprepper.plugins.processor.ServiceMapStatefulProcessor.evaluateEdges(ServiceMapStatefulProcessor.java:169)
at com.amazon.dataprepper.plugins.processor.ServiceMapStatefulProcessor.execute(ServiceMapStatefulProcessor.java:98)
at com.amazon.dataprepper.pipeline.ProcessWorker.run(ProcessWorker.java:53)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.channels.OverlappingFileLockException
at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1154)
at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1165)
at org.mapdb.volume.Volume.lockFile(Volume.java:490)
... 19 more
180647 [service-map-pipeline-process-worker-2-thread-1] ERROR com.amazon.dataprepper.pipeline.ProcessWorker  ? Encountered exception during pipeline processing
org.mapdb.DBException$FileLocked: File is already opened and is locked: data/service-map/trace-db-1612972144660
at org.mapdb.volume.Volume.lockFile(Volume.java:495)
at org.mapdb.volume.MappedFileVol.<init>(MappedFileVol.java:88)
at org.mapdb.volume.MappedFileVol$MappedFileFactory.factory(MappedFileVol.java:64)
at org.mapdb.volume.MappedFileVol$MappedFileFactory.makeVolume(MappedFileVol.java:38)
at org.mapdb.StoreDirect$volume$1.invoke(StoreDirect.kt:77)
at org.mapdb.StoreDirect$volume$1.invoke(StoreDirect.kt:16)
at org.mapdb.StoreDirect.<init>(StoreDirect.kt:76)
at org.mapdb.StoreDirect$Companion.make(StoreDirect.kt:57)
at org.mapdb.StoreDirect$Companion.make$default(StoreDirect.kt:56)
at org.mapdb.DBMaker$Maker.make(DBMaker.kt:450)
at com.amazon.dataprepper.plugins.processor.state.MapDbProcessorState.<init>(MapDbProcessorState.java:39)
at com.amazon.dataprepper.plugins.processor.ServiceMapStatefulProcessor.rotateWindows(ServiceMapStatefulProcessor.java:300)
at com.amazon.dataprepper.plugins.processor.ServiceMapStatefulProcessor.evaluateEdges(ServiceMapStatefulProcessor.java:169)
at com.amazon.dataprepper.plugins.processor.ServiceMapStatefulProcessor.execute(ServiceMapStatefulProcessor.java:98)
at com.amazon.dataprepper.pipeline.ProcessWorker.run(ProcessWorker.java:53)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.channels.OverlappingFileLockException
at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1154)
at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1165)
at org.mapdb.volume.Volume.lockFile(Volume.java:490)
... 19 more

```

**Comment by kowshikn** [comment]
Findings so far: Service-map processor is created only once and and used by worker-threads and this clearly causes the race condition as every thread tried to rotate. At this point setting workers to N>1 only causes more issues than parallelism.

Plan: I don't know where we missed it, but this clearly is not the end goal we wanted to achieve. Rather than quickly fixing lets try to target this for next release. For this release the ec2 cfn template uses 1 worker for the service-map, the only thing pending is update README to reflect the same.

**Comment by chenqi0805** [comment]
Issue: Current ServiceMapStateful assumes one instance confined to a single thread while data-prepper-api allows all workers to access a shared prepper.

Discussion on solution offline: We need a way to parallelize prepper processing while still maintaining threadsafety for stateful preppers.

Approach 1. Confine individual prepper and sink instance to a thread/runnable. Currently a prepper instance that implements AbstractPrepper is shared across all workers, in this approach we confine it to a thread/runnable.

Pros: 
1. No threadsafe requirement for developers implement AbstractPrepper or AbstractSink since an instance is only accessed by a single thread
2. Compatible with current ServicemapStatefulPrepper implementation. 

Cons:
Might need big refactoring of data-prepper-api.

Approach 2. Let the stateful prepper manage parallelization by itself. We still allow a prepper to be shared by all workers. 

Pros:
No big refactoring of current data-prepper-api

Cons:
1. Stateful prepper has threadsafe implementation overhead.
2. More vulnerable for a prepper to break the fixed number of workers restriction imposed at pipeline level.

**Comment by kowshikn** [comment]
I would prefer approach 1 and do it only for stateful prepper.
