### ISSUE TITLE
Peer forwarder - domain name validation

### ISSUE THREAD

**Issue by wrijeff** [opendistro-for-elasticsearch/data-prepper#437]
Invalid domain names (e.g. '127_543.5.6') can cause a crash like:
```
2021-03-17T15:40:56,348 [entry-pipeline-process-worker-1-thread-1] ERROR com.amazon.dataprepper.pipeline.ProcessWorker - Encountered exception during pipeline processing
java.lang.IllegalArgumentException: Not a valid domain name: '127_543.5.6'
        at com.linecorp.armeria.internal.shaded.guava.base.Preconditions.checkArgument(Preconditions.java:217) ~[data-prepper.jar:0.8.0]
        at com.linecorp.armeria.internal.shaded.guava.net.InternetDomainName.<init>(InternetDomainName.java:149) ~[data-prepper.jar:0.8.0]
        at com.linecorp.armeria.internal.shaded.guava.net.InternetDomainName.from(InternetDomainName.java:210) ~[data-prepper.jar:0.8.0]
        at com.linecorp.armeria.client.Endpoint.create(Endpoint.java:125) ~[data-prepper.jar:0.8.0]
        at com.linecorp.armeria.client.Endpoint.parse(Endpoint.java:84) ~[data-prepper.jar:0.8.0]
        at com.linecorp.armeria.client.DefaultClientBuilderParams.<init>(DefaultClientBuilderParams.java:55) ~[data-prepper.jar:0.8.0]
        at com.linecorp.armeria.client.ClientBuilderParams.of(ClientBuilderParams.java:40) ~[data-prepper.jar:0.8.0]
        at com.linecorp.armeria.client.ClientBuilder.build(ClientBuilder.java:109) ~[data-prepper.jar:0.8.0]
        at com.amazon.dataprepper.plugins.prepper.peerforwarder.PeerClientPool.createGRPCClient(PeerClientPool.java:58) ~[data-prepper.jar:0.8.0]
        at com.amazon.dataprepper.plugins.prepper.peerforwarder.PeerClientPool.lambda$getClient$0(PeerClientPool.java:43) ~[data-prepper.jar:0.8.0]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at com.amazon.dataprepper.plugins.prepper.peerforwarder.PeerClientPool.getClient(PeerClientPool.java:43) ~[data-prepper.jar:0.8.0]
        at com.amazon.dataprepper.plugins.prepper.peerforwarder.PeerForwarder.doExecute(PeerForwarder.java:94) ~[data-prepper.jar:0.8.0]
        at com.amazon.dataprepper.plugins.prepper.peerforwarder.PeerForwarder.doExecute(PeerForwarder.java:27) ~[data-prepper.jar:0.8.0]
        at com.amazon.dataprepper.model.prepper.AbstractPrepper.lambda$execute$0(AbstractPrepper.java:39) ~[data-prepper.jar:0.8.0]
        at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:57) ~[data-prepper.jar:0.8.0]
        at com.amazon.dataprepper.model.prepper.AbstractPrepper.execute(AbstractPrepper.java:39) ~[data-prepper.jar:0.8.0]
        at com.amazon.dataprepper.pipeline.ProcessWorker.run(ProcessWorker.java:57) [data-prepper.jar:0.8.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

We should protect against this in case an invalid domain name is configured either via static list or returned by the DNS queries. Would probably be better to log an error/emit metrics instead of stopping the entire application. 

Simple string validation with error handling should be sufficient.

**Comment by chenqi0805** [comment]
Close via #534
