### ISSUE TITLE
Trace Analytics Sample App not generating traces

### ISSUE THREAD

**Issue by joshuali925** [opendistro-for-elasticsearch/data-prepper#452]
**Describe the bug**
Using pre-release artifacts from jeff [here](https://github.com/wrijeff/simple-ingest-transformation-utility-pipeline/releases/tag/temp2), after generating about 300-500 spans, clicking buttons in the sample app doesn't export more spans to elasticsearch.

**To Reproduce**
1. Download and follow instructions from https://github.com/wrijeff/simple-ingest-transformation-utility-pipeline/releases/tag/temp2, start ES, Kibana, docker-compose
2. In `Trace Analytics Sample App` click on `CHECKOUT`, `CANCEL`, `CREATE`, `STATUS`, `PAY` until number of documents reach ~400
3. Keep clicking and no new documents show up
4. Shutdown everything, wait some time and restart, the sample app works for another ~400 spans.

**Expected behavior**
Sample app should keep working

**Screenshots**
I see this error in docker but not sure if is relevant
```
sample-app_1      | [opentelemetry.auto.trace 2021-03-22 21:37:58:014 +0000] [grpc-default-executor-4] WARN io.opentelemetry.exporter.otlp.OtlpGrpcMetricExporter - Failed to export metrics
sample-app_1      | io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service opentelemetry.proto.collector.metrics.v1.MetricsService
sample-app_1      |     at io.grpc.Status.asRuntimeException(Status.java:533)
sample-app_1      |     at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:515)
sample-app_1      |     at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
sample-app_1      |     at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
sample-app_1      |     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
sample-app_1      |     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
sample-app_1      |     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
sample-app_1      |     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
sample-app_1      |     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
sample-app_1      |     at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
sample-app_1      |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
sample-app_1      |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
sample-app_1      |     at java.lang.Thread.run(Thread.java:748)
```

**Environment (please complete the following information):**
Amazon Linux 2, ES 7.10.2 oss version (no security)

**Additional context**

**Comment by chenqi0805** [comment]
Tested with main. The issue has not shown up by docker run: 
![Screen Shot 2021-03-30 at 9 52 41 AM](https://user-images.githubusercontent.com/19492223/113009762-de16c980-913d-11eb-930f-23cfcaab5817.png)

> I see this error in docker but not sure if is relevant

The traceback is not relevant. Currently we have not supported metrics export from otel-collector.
