### ISSUE TITLE
invalid_alias_name_exception on Data Prepper startup

### ISSUE THREAD

**Issue by wrijeff** [opendistro-for-elasticsearch/data-prepper#491]
**Describe the bug**
An ES cluster got into a weird state when an index was created named `otel-v1-apm-span` even though this name is intended to be reserved for an index _alias_. 

```
{"error":{"root_cause":[{"type":"invalid_alias_name_exception","reason":"Invalid alias name [otel-v1-apm-span], an index exists with the same name as the alias","index_uuid":"0-ZhKKdyRHeJjw4QKjF-Yg","index":"otel-v1-apm-span"}],"type":"invalid_alias_name_exception","reason":"Invalid alias name [otel-v1-apm-span], an index exists with the same name as the alias","index_uuid":"0-ZhKKdyRHeJjw4QKjF-Yg","index":"otel-v1-apm-span"},"status":400}
```
Refer to #479 for more information. We should determine how to get to this invalid state and find if there's anything we can do to code around it. Or at the very least provide a more useful error message indicating that the index needs to be manually deleted.

**Comment by chenqi0805** [comment]
steps to reproduce the bug by `examples/dev/trace-analytics-sample-app`:

1. start all containers as normal: `docker-compose up -d`
2. In the Kibana interactive console, run `DELETE otel-v1-apm-span-*`
3. open `localhost:8089` and start sending traces by clicking the buttons. verify in the kibana dashboard that an index was created named `otel-v1-apm-span`: 
![Screen Shot 2021-05-12 at 2 28 46 PM](https://user-images.githubusercontent.com/19492223/118034373-85873e80-b32f-11eb-8c99-58175cb30d82.png)

4. docker restart data-prepper container
5. check data-prepper log: 
```
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
        at com.amazon.dataprepper.plugins.PluginFactory.newPlugin(PluginFactory.java:24) ~[data-prepper.jar:0.8.0-beta]
        at com.amazon.dataprepper.plugins.sink.SinkFactory.newSink(SinkFactory.java:12) ~[data-prepper.jar:0.8.0-beta]
        at com.amazon.dataprepper.parser.PipelineParser.buildSinkOrConnector(PipelineParser.java:149) ~[data-prepper.jar:0.8.0-beta]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) [?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) [?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) [?:?]
        at com.amazon.dataprepper.parser.PipelineParser.buildPipelineFromConfiguration(PipelineParser.java:98) [data-prepper.jar:0.8.0-beta]
        at com.amazon.dataprepper.parser.PipelineParser.parseConfiguration(PipelineParser.java:64) [data-prepper.jar:0.8.0-beta]
        at com.amazon.dataprepper.DataPrepper.execute(DataPrepper.java:97) [data-prepper.jar:0.8.0-beta]
        at com.amazon.dataprepper.DataPrepperExecute.main(DataPrepperExecute.java:20) [data-prepper.jar:0.8.0-beta]
Caused by: org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=invalid_alias_name_exception, reason=Invalid alias name [otel-v1-apm-span], an index exists with the same name as the alias]
        at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:187) ~[data-prepper.jar:0.8.0-beta]
        at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1911) ~[data-prepper.jar:0.8.0-beta]
        at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1888) ~[data-prepper.jar:0.8.0-beta]
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1645) ~[data-prepper.jar:0.8.0-beta]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1617) ~[data-prepper.jar:0.8.0-beta]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1584) ~[data-prepper.jar:0.8.0-beta]
        at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:145) ~[data-prepper.jar:0.8.0-beta]
        at com.amazon.dataprepper.plugins.sink.elasticsearch.ElasticsearchSink.checkAndCreateIndex(ElasticsearchSink.java:185) ~[data-prepper.jar:0.8.0-beta]
        at com.amazon.dataprepper.plugins.sink.elasticsearch.ElasticsearchSink.start(ElasticsearchSink.java:90) ~[data-prepper.jar:0.8.0-beta]
        at com.amazon.dataprepper.plugins.sink.elasticsearch.ElasticsearchSink.<init>(ElasticsearchSink.java:72) ~[data-prepper.jar:0.8.0-beta]
        ... 19 more
        Suppressed: org.elasticsearch.client.ResponseException: method [PUT], host [https://node-0.example.com:9200], URI [/otel-v1-apm-span-000001?master_timeout=30s&timeout=30s], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"invalid_alias_name_exception","reason":"Invalid alias name [otel-v1-apm-span], an index exists with the same name as the alias","index_uuid":"hxpVwQzHQOm7CEayMCCHAw","index":"otel-v1-apm-span"}],"type":"invalid_alias_name_exception","reason":"Invalid alias name [otel-v1-apm-span], an index exists with the same name as the alias","index_uuid":"hxpVwQzHQOm7CEayMCCHAw","index":"otel-v1-apm-span"},"status":400}
                at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326) ~[data-prepper.jar:0.8.0-beta]
                at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296) ~[data-prepper.jar:0.8.0-beta]
                at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) ~[data-prepper.jar:0.8.0-beta]
                at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1632) ~[data-prepper.jar:0.8.0-beta]
                at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1617) ~[data-prepper.jar:0.8.0-beta]
                at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1584) ~[data-prepper.jar:0.8.0-beta]
                at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:145) ~[data-prepper.jar:0.8.0-beta]
                at com.amazon.dataprepper.plugins.sink.elasticsearch.ElasticsearchSink.checkAndCreateIndex(ElasticsearchSink.java:185) ~[data-prepper.jar:0.8.0-beta]
                at com.amazon.dataprepper.plugins.sink.elasticsearch.ElasticsearchSink.start(ElasticsearchSink.java:90) ~[data-prepper.jar:0.8.0-beta]
                at com.amazon.dataprepper.plugins.sink.elasticsearch.ElasticsearchSink.<init>(ElasticsearchSink.java:72) ~[data-prepper.jar:0.8.0-beta]
                at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[?:?]
                at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
                at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
                at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
                at com.amazon.dataprepper.plugins.PluginFactory.newPlugin(PluginFactory.java:24) ~[data-prepper.jar:0.8.0-beta]
                at com.amazon.dataprepper.plugins.sink.SinkFactory.newSink(SinkFactory.java:12) ~[data-prepper.jar:0.8.0-beta]
                at com.amazon.dataprepper.parser.PipelineParser.buildSinkOrConnector(PipelineParser.java:149) ~[data-prepper.jar:0.8.0-beta]
                at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
                at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) [?:?]
                at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
                at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
                at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) [?:?]
                at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
                at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) [?:?]
                at com.amazon.dataprepper.parser.PipelineParser.buildPipelineFromConfiguration(PipelineParser.java:98) [data-prepper.jar:0.8.0-beta]
                at com.amazon.dataprepper.parser.PipelineParser.parseConfiguration(PipelineParser.java:64) [data-prepper.jar:0.8.0-beta]
                at com.amazon.dataprepper.DataPrepper.execute(DataPrepper.java:97) [data-prepper.jar:0.8.0-beta]
                at com.amazon.dataprepper.DataPrepperExecute.main(DataPrepperExecute.java:20) [data-prepper.jar:0.8.0-beta]
```

**Comment by chenqi0805** [comment]
Root cause: when data-prepper ElasticsearchSink is ingesting span docs by making bulk request, it is made through the index alias `otel-v1-apm-span`. If the underlying indices `otel-v1-apm-span-*` get deleted by accident in the process,  the index alias that bulk requests are made through will be identified as a new index by mistake. Thus ODFE is in an invalid state for data-prepper. When data-prepper restarts, it identifies that alias `otel-v1-apm-span` does not exist and then tries to create index `otel-v1-apm-span-000001` labeled by the alias name `otel-v1-apm-span`. But it turns out there is already an index named `otel-v1-apm-span`. Thus the traceback: `"reason":"Invalid alias name [otel-v1-apm-span], an index exists with the same name as the alias"`

Overall, it is expected that the raw span and service-map indices should not be intervened manually unless there are verified remediation steps. Otherwise there could be more scenarios of invalid states that will cause data-prepper to fail.

**Comment by wrijeff** [comment]
Thanks @chenqi0805 for digging in to this issue. How difficult would it be to catch this specific failure and display something more informative to the user in the logs?

**Comment by chenqi0805** [comment]
We can try to catch `Invalid alias name [otel-v1-apm-span], an index exists with the same name as the alias` in `checkAndCreateIndex` IOException and tell user to delete or migrate the index.
